"""change_constraint_caster

Revision ID: b1fcfd3ff8cf
Revises: e4ce81a8533f
Create Date: 2024-09-06 08:54:39.162495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1fcfd3ff8cf'
down_revision: Union[str, None] = 'e4ce81a8533f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('l_caster_class_caster_id_fkey', 'l_caster_class', type_='foreignkey')
    op.create_foreign_key(None, 'l_caster_class', 'g_caster', ['caster_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'l_caster_class', type_='foreignkey')
    op.create_foreign_key('l_caster_class_caster_id_fkey', 'l_caster_class', 'g_caster', ['caster_id'], ['id'])
    # ### end Alembic commands ###
