"""create_d_class_and_d_subclass

Revision ID: c450fe6a4a31
Revises: 
Create Date: 2024-08-19 12:37:20.402547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c450fe6a4a31'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('d_class',
    sa.Column('alias', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('choose_subclass_level', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('alias')
    )
    op.create_table('d_subclass',
    sa.Column('class_alias', sa.String(length=32), nullable=False),
    sa.Column('alias', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['class_alias'], ['d_class.alias'], ),
    sa.PrimaryKeyConstraint('alias')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('d_subclass')
    op.drop_table('d_class')
    # ### end Alembic commands ###
