"""create_caster_tables

Revision ID: e4ce81a8533f
Revises: c450fe6a4a31
Create Date: 2024-08-25 09:26:07.899983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4ce81a8533f'
down_revision: Union[str, None] = 'c450fe6a4a31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('g_caster',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('intelligence', sa.SmallInteger(), nullable=True),
    sa.Column('wisdom', sa.SmallInteger(), nullable=True),
    sa.Column('charisma', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('l_caster_class',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('caster_id', sa.Integer(), nullable=False),
    sa.Column('class_alias', sa.String(length=32), nullable=False),
    sa.Column('subclass_alias', sa.String(length=32), nullable=True),
    sa.Column('level', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['caster_id'], ['g_caster.id'], ),
    sa.ForeignKeyConstraint(['class_alias'], ['d_class.alias'], ),
    sa.ForeignKeyConstraint(['subclass_alias'], ['d_subclass.alias'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('l_caster_class')
    op.drop_table('g_caster')
    # ### end Alembic commands ###
