"""create_spell_and_liked_tables

Revision ID: f0a4e56301c7
Revises: b1fcfd3ff8cf
Create Date: 2025-01-10 07:32:03.040214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0a4e56301c7'
down_revision: Union[str, None] = 'b1fcfd3ff8cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('d_game_class_type',
    sa.Column('alias', sa.String(length=32), nullable=False),
    sa.Column('class_level', sa.SmallInteger(), nullable=False),
    sa.Column('cell_level', sa.SmallInteger(), nullable=False),
    sa.Column('cell_add_amount', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('alias', 'class_level', 'cell_level')
    )
    op.create_table('d_spell',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    op.create_table('dl_spell_availability',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spell_id', sa.Integer(), nullable=False),
    sa.Column('class_alias', sa.String(length=32), nullable=False),
    sa.Column('subclass_alias', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['class_alias'], ['d_class.alias'], ),
    sa.ForeignKeyConstraint(['spell_id'], ['d_spell.id'], ),
    sa.ForeignKeyConstraint(['subclass_alias'], ['d_subclass.alias'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('d_class', sa.Column('type', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('d_class', 'type')
    op.drop_table('dl_spell_availability')
    op.drop_table('d_spell')
    op.drop_table('d_game_class_type')
    # ### end Alembic commands ###
